apiVersion: v1
kind: Pod
metadata:
  name: password-client
spec:
  containers:
    - name: psql
      image: postgres:17-alpine
      command: [sh, -c, 'sleep 7200']
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef: {name: application-password, key: password}
      resources:
        requests: {cpu: 5m, memory: 16Mi}
        limits: {cpu: 100m, memory: 64Mi}
