apiVersion: v1
kind: Pod
metadata:
  name: campus-web-pod
  labels:
    app: campus-web
    tier: frontend
spec:
  containers:
    - name: web
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
