apiVersion: v1
kind: Service
metadata:
  name: campus-db
spec:
  clusterIP: None
  selector:
    app: campus-db
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: campus-db
spec:
  serviceName: campus-db
  replicas: 2
  selector:
    matchLabels:
      app: campus-db
  template:
    metadata:
      labels:
        app: campus-db
    spec:
      containers:
        - name: db
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
