apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-data
  namespace: assignment-s13
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi
