apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: session20
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/vimalyad/devops-heros.git
  destinations:
  - namespace: assignment-s20
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: session20
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: session20
  source:
    repoURL: https://github.com/vimalyad/devops-heros.git
    targetRevision: assignment/session20-observability-gitops
    path: session-20-observability-gitops/Vimal-24BCS10273/gitops/application
  destination:
    server: https://kubernetes.default.svc
    namespace: assignment-s20
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
