apiVersion: v1
kind: Service
metadata:
  name: yatri-backend-service
  labels:
    app: yatri-backend
spec:
  type: ClusterIP
  selector:
    app: yatri-backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
