apiVersion: v1
kind: Service
metadata:
  name: app-rolling-service
  labels:
    app: app-rolling
spec:
  type: NodePort
  selector:
    app: app-rolling
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30010
      protocol: TCP
