apiVersion: v1
kind: Pod
metadata:
  name: lc-image-error
spec:
  restartPolicy: Always
  containers:
  - name: app
    image: busybox:assignment-tag-does-not-exist
    command:
    - sh
    - -c
    - sleep 7200
    resources:
      requests:
        cpu: 5m
        memory: 8Mi
      limits:
        cpu: 100m
        memory: 32Mi
