apiVersion: v1
kind: Pod
metadata:
  name: lc-init
spec:
  restartPolicy: Always
  containers:
  - name: app
    image: busybox:1.37
    command:
    - sh
    - -c
    - cat /shared/seed.txt; sleep 7200
    resources:
      requests:
        cpu: 5m
        memory: 8Mi
      limits:
        cpu: 100m
        memory: 32Mi
    volumeMounts:
    - name: shared
      mountPath: /shared
  initContainers:
  - name: seed
    image: busybox:1.37
    command:
    - sh
    - -c
    - echo "preparing seed"; sleep 8; echo "seed ready" > /shared/seed.txt
    resources:
      requests:
        cpu: 5m
        memory: 8Mi
      limits:
        cpu: 100m
        memory: 32Mi
    volumeMounts:
    - name: shared
      mountPath: /shared
  volumes:
  - name: shared
    emptyDir: {}
